import { FormEvent, useEffect, useState } from 'react'
import { DEMO_UNITS } from './demoUnits'
import { AdminUser, AdminAuditEvent, adminLogout, createAdminUser, listAdminUsers, setAdminUserActive, resetAdminUserPassword, getAdminAudit, updateAdminUserAccess } from './api'

const roles:Record<string,string>={admin:'Administrador',operacao:'Operação',nutricao:'Nutrição',visualizacao:'Visualização'}
export function AdminUsersPage(){
 const [users,setUsers]=useState<AdminUser[]>([]);const [events,setEvents]=useState<AdminAuditEvent[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const [form,setForm]=useState({name:'',email:'',password:'',role:'operacao'})
 const [selectedUnits,setSelectedUnits]=useState<string[]>([])
 const [editing,setEditing]=useState<string|null>(null)
 const [editRole,setEditRole]=useState('operacao')
 const [editUnits,setEditUnits]=useState<string[]>([])
 const load=()=>Promise.all([listAdminUsers(),getAdminAudit()]).then(([r,a])=>{setUsers(r.users);setEvents(a.events)}).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar usuários.'))
 useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await createAdminUser({...form,unit_ids:form.role==='admin'?[]:selectedUnits});setForm({name:'',email:'',password:'',role:'operacao'});setSelectedUnits([]);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar usuário.')}finally{setBusy(false)}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">A</span><div><strong>APETIT</strong><small>Admin</small></div></div><nav><button className="nav-item" onClick={()=>location.hash='visao-geral'}>⌂ Visão geral</button><button className="nav-item active">♙ Usuários e acessos</button></nav></aside><main className="main">
 <header className="topbar"><div><span className="eyebrow">GESTÃO · ACESSOS</span><h1>Usuários e permissões</h1><p>Crie contas individuais para tornar as ações do Admin rastreáveis.</p></div><button className="secondary" onClick={async()=>{try{await adminLogout()}catch{}finally{location.hash="usuarios";location.reload()}}}>Sair</button></header>
 {error&&<div className="alert error">{error}</div>}
 <section className="card content-card"><div className="section-heading"><div><h2>Novo usuário</h2><p>Administrador gerencia acessos; Operação publica/restaura; Nutrição publica e mantém fichas; Visualização apenas consulta.</p></div></div>
 <form className="form-grid" onSubmit={submit}><label><span>Nome</span><input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>E-mail</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span>Senha inicial</span><input required type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label><span>Perfil</span><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{form.role!=='admin'&&<fieldset className="unit-access-field"><legend>Unidades autorizadas</legend><p>Marque as unidades às quais esta conta terá acesso. Sem seleção, não terá acesso a unidades.</p><div className="unit-access-options">{DEMO_UNITS.map(unit=><label key={unit.unitId}><input type="checkbox" checked={selectedUnits.includes(unit.unitId)} onChange={e=>setSelectedUnits(current=>e.target.checked?[...current,unit.unitId]:current.filter(id=>id!==unit.unitId))}/><span>{unit.company}</span></label>)}</div></fieldset>}<button className="primary" disabled={busy}>{busy?'Criando...':'Criar usuário'}</button></form></section>
 <section className="card history-card"><div className="section-heading"><div><span className="eyebrow">EQUIPE</span><h2>{users.length} usuário(s)</h2></div></div><div className="user-list">{users.map(u=><article className="user-row" key={u.id??u.email??u.name}><div><strong>{u.name}</strong><small>{u.email}</small></div><span className="badge soft">{roles[u.role]??u.role}</span><span className={u.active===false?'badge':'status-pill'}>{u.active===false?'Inativo':'Ativo'}</span><div><small>{u.role==='admin'?'Todas as unidades':(u.unit_ids?.length?`${u.unit_ids.length} unidade(s)`:'Sem unidade')}</small></div><div className="user-actions"><button type="button" onClick={()=>{if(!u.id)return;setEditing(u.id);setEditRole(u.role);setEditUnits(u.unit_ids??[]);setError('')}}>Editar acesso</button><button type="button" onClick={async()=>{if(!u.id)return;try{await setAdminUserActive(u.id,u.active===false);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar acesso')}}}>{u.active===false?'Ativar':'Desativar'}</button><button type="button" onClick={async()=>{if(!u.id)return;const password=window.prompt('Nova senha (mínimo 8 caracteres):');if(!password)return;if(password.length<8){setError('A senha precisa ter pelo menos 8 caracteres.');return}try{await resetAdminUserPassword(u.id,password);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao redefinir senha')}}}>Redefinir senha</button></div>{editing===u.id&&<div className="access-editor"><h3>Editar permissões de {u.name}</h3><label><span>Perfil</span><select value={editRole} onChange={e=>setEditRole(e.target.value)}>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{editRole!=='admin'&&<fieldset className="unit-access-field"><legend>Unidades autorizadas</legend><div className="unit-access-options">{DEMO_UNITS.map(unit=><label key={unit.unitId}><input type="checkbox" checked={editUnits.includes(unit.unitId)} onChange={e=>setEditUnits(current=>e.target.checked?[...current,unit.unitId]:current.filter(id=>id!==unit.unitId))}/><span>{unit.company}</span></label>)}</div></fieldset>}<div className="access-editor-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button type="button" className="primary" disabled={busy} onClick={async()=>{if(!u.id)return;setBusy(true);setError('');try{await updateAdminUserAccess(u.id,editRole,editRole==='admin'?[]:editUnits);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar permissões')}finally{setBusy(false)}}}>Salvar permissões</button></div></div>}</article>)}</div></section>
 <section className="card history-card"><div className="section-heading"><h2>Auditoria de acessos</h2></div><div className="user-list">{events.map(e=><article className="user-row" key={e.id}><div><strong>{e.action}</strong><small>{e.actor_name??'Operador não identificado'} · {new Date(e.created_at).toLocaleString('pt-BR')}</small></div><small>{e.resource_id}</small></article>)}</div></section></main></div>
}
